# Generated by Django 5.0.6 on 2024-07-26 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArt', models.CharField(max_length=5)),
                ('nomArt', models.CharField(max_length=30)),
                ('precioArt', models.FloatField()),
                ('material', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idVenta', models.CharField(max_length=5)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('idCliente', models.CharField(max_length=5)),
                ('idArt', models.CharField(max_length=5)),
                ('cant', models.IntegerField(null=True)),
                ('montoVta', models.FloatField(null=True)),
                ('tipoPago', models.CharField(max_length=10)),
            ],
        ),
    ]
